### ISSUE TITLE
CSS partially not applying

### ISSUE THREAD

**Issue by actuallymentor** [peterdemartini/html5-to-pdf#34]
Hello!

Thanks for this wonderful module.

I noticed that when I apply:

```css
thead { background: lightgrey!important; }
```

But tables render without the background color for the headings. Note that other css (same stylesheet) is rendering just fine, and I assume that the !important overrides directives inside the template.

Is this a known issue?
